export { default as AddEditAssignmentModal } from './AddEditAssignmentModal';
export { default as AddEditClassModal } from './AddEditClassModal';
export { default as AddEditDepartmentModal } from './AddEditDepartmentModal';
export { default as QuickEditSection } from './QuickEditSection';
export { default as AddEditSectionModal } from './AddEditSectionModal';
export { default as AddEditSubjectModal } from './AddEditSubjectModal';
export { default as ViewModal } from './ViewModal';
export { default as AssignmentManagement } from './AssignmentManagement';
export { default as EntityManagement } from './EntityManagement';
